import { toast } from "sonner";
import { PATIENT, ZONE_LABELS, type SymptomEntry } from "@/lib/painpoint-data";

type Props = {
  symptoms: SymptomEntry[];
};

export function DoctorExport({ symptoms }: Props) {
  // Group symptoms by zone and calculate summaries
  const symptomEntries = symptoms.filter((s) => s.kind === "symptom" && s.zone);
  const grouped = symptomEntries.reduce<Record<string, SymptomEntry[]>>((acc, s) => {
    const key = s.zone!;
    if (!acc[key]) acc[key] = [];
    acc[key].push(s);
    return acc;
  }, {});

  const ACTIONS = [
    { label: "Download PDF", msg: "PDF ready for download.", primary: true },
    { label: "Share via WhatsApp", msg: "WhatsApp share opened.", primary: false },
    { label: "Send to DA Doctor", msg: "Report sent to Doctor Anywhere.", primary: false },
  ];

  return (
    <div className="space-y-4">
      <div
        className="pp-card rounded-2xl p-5"
        style={{ animation: "fade-up 320ms cubic-bezier(0.22,1,0.36,1) both" }}
      >
        <div className="flex items-start justify-between gap-3">
          <div>
            <p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-pp-teal-deep">
              Symptom Report
            </p>
            <h2 className="font-display mt-0.5 text-2xl font-medium tracking-tight">
              {PATIENT.name}, {PATIENT.age}
            </h2>
            <p className="text-xs text-muted-foreground">
              Period: 17–24 May 2026 · Generated by PainPoint
            </p>
          </div>
          <span className="font-display grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-gradient-to-br from-pp-teal to-pp-blue text-base font-semibold text-white shadow">
            AK
          </span>
        </div>

        <div className="pp-divider-glow my-4 h-px w-full" />

        <div className="space-y-1.5 text-sm">
          <p>
            <span className="font-semibold">Known Conditions:</span>{" "}
            <span className="text-muted-foreground">{PATIENT.conditions.join(", ")}</span>
          </p>
          <p>
            <span className="font-semibold">Medications:</span>{" "}
            <span className="text-muted-foreground">{PATIENT.medications.join(", ")}</span>
          </p>
        </div>

        <div className="pp-divider-glow my-4 h-px w-full" />

        <h3 className="text-[11px] font-semibold uppercase tracking-[0.2em] text-muted-foreground">
          Symptom Summary
        </h3>
        <ul className="mt-2 space-y-2 text-sm">
          {Object.entries(grouped).map(([zone, entries]) => {
            const zoneLabel = ZONE_LABELS[zone as keyof typeof ZONE_LABELS]?.en || zone;
            const types = [...new Set(entries.map((e) => e.type))].filter(Boolean).join(", ");
            const severities = [...new Set(entries.map((e) => e.severity))]
              .filter(Boolean)
              .join(", ");
            const answers = entries
              .map((e) => e.answer)
              .filter(Boolean)
              .join(", ");
            const trend =
              entries.length >= 3
                ? "Increasing frequency ↑"
                : entries.length === 1
                  ? "Single occurrence"
                  : "Stable →";
            return (
              <li key={zone} className="rounded-xl bg-muted/30 px-3 py-2">
                <span className="font-semibold">
                  {zoneLabel} ({types}):
                </span>{" "}
                {entries.length} episode{entries.length > 1 ? "s" : ""}, {severities}
                {answers && <span>, {answers}</span>}
                <div className="mt-0.5 text-xs text-muted-foreground">Trend: {trend}</div>
              </li>
            );
          })}
        </ul>

        {grouped["chest"] && grouped["chest"].length >= 3 && (
          <div className="pp-amber-card mt-4 rounded-xl p-3 text-sm">
            <p className="font-bold">⚠️ Pattern Alert</p>
            <p>
              Chest pressing symptoms recurring {grouped["chest"].length}× in 7 days. Recommend
              clinical review.
            </p>
          </div>
        )}

        <p className="mt-4 text-xs italic text-muted-foreground">
          Generated by PainPoint. Not a diagnosis. Please confirm with clinical assessment.
        </p>
      </div>

      <div className="grid grid-cols-1 gap-2 sm:grid-cols-3">
        {ACTIONS.map((b) => (
          <button
            key={b.label}
            onClick={() => toast.success(b.msg)}
            className={
              b.primary
                ? "pp-primary-button h-12 rounded-xl text-sm font-bold"
                : "pp-soft-button h-12 rounded-xl border border-pp-teal/30 text-sm font-bold text-pp-teal-deep"
            }
          >
            {b.label}
          </button>
        ))}
      </div>
    </div>
  );
}
